"""Configurações e constantes para o pipeline de dados de alvarás de SP."""

from typing import List, Dict

DISTRITOS_SP: List[str] = [
    'AGUA RASA', 'ALTO DE PINHEIROS', 'ANHANGUERA', 'ARICANDUVA', 'ARTUR ALVIM',
    'BARRA FUNDA', 'BELA VISTA', 'BELEM', 'BOM RETIRO', 'BRAS', 'BRASILANDIA',
    'BUTANTA', 'CACHOEIRINHA', 'CAMBUCI', 'CAMPO BELO', 'CAMPO GRANDE', 'CAMPO LIMPO',
    'CANGAIBA', 'CAPAO REDONDO', 'CARRAO', 'CASA VERDE', 'CIDADE ADEMAR', 'CIDADE DUTRA',
    'CIDADE LIDER', 'CIDADE TIRADENTES', 'CONSOLACAO', 'CURSINO', 'ERMELINO MATARAZZO',
    'FREGUESIA DO O', 'GRAJAU', 'GUAIANASES', 'IGUATEMI', 'IPIRANGA', 'ITAIM BIBI',
    'ITAIM PAULISTA', 'ITAQUERA', 'JABAQUARA', 'JACANA', 'JAGUARA', 'JAGUARE',
    'JARAGUA', 'JARDIM ANGELA', 'JARDIM HELENA', 'JARDIM PAULISTA', 'JARDIM SAO LUIS',
    'JOSE BONIFACIO', 'LAJEADO', 'LAPA', 'LIBERDADE', 'LIMAO', 'MANDAQUI', 'MARSILAC',
    'MOEMA', 'MOOCA', 'MORUMBI', 'PARELHEIROS', 'PARI', 'PARQUE DO CARMO', 'PEDREIRA',
    'PENHA', 'PERDIZES', 'PERUS', 'PINHEIROS', 'PONTE RASA', 'PIRITUBA', 'RAPOSO TAVARES',
    'REPUBLICA', 'RIO PEQUENO', 'SACOMA', 'SANTA CECILIA', 'SANTANA', 'SANTO AMARO',
    'SAO DOMINGOS', 'SAO LUCAS', 'SAO MATEUS', 'SAO MIGUEL', 'SAO RAFAEL', 'SAPOPEMBA',
    'SAUDE', 'SE', 'SOCORRO', 'TATUAPE', 'TREMEMBE', 'TUCURUVI', 'VILA ANDRADE',
    'VILA CURUCA', 'VILA FORMOSA', 'VILA GUILHERME', 'VILA JACUI', 'VILA LEOPOLDINA',
    'VILA MARIA', 'VILA MARIANA', 'VILA MATILDE', 'VILA MEDEIROS', 'VILA PRUDENTE', 'VILA SONIA'
]

CENTRO_EXPANDIDO: List[str] = [
    'REPUBLICA', 'SE', 'BELA VISTA', 'CONSOLACAO', 'SANTA CECILIA', 'BOM RETIRO', 'CAMBUCI',
    'PINHEIROS', 'PERDIZES', 'LAPA', 'BARRA FUNDA', 'VILA MARIANA', 'MOEMA', 'ITAIM BIBI',
    'JARDINS', 'MOOCA', 'BRAS', 'PARI', 'IPIRANGA', 'LIBERDADE'
]

DICIONARIO_MANUAL: Dict[str, str] = {
    'SAO MIGUEL PAULISTA': 'SAO MIGUEL',
    'CANGAIBA': 'PENHA',
    'VILA CARRAO': 'CARRAO',
    'CITY JARAGUA': 'JARAGUA'
}

COLUNAS_FINAIS: List[str] = [
    'id', 'legislacao', 'area_do_terreno', 'area_da_unidade', 
    'ano_execucao', 'n_unidades', 'categoria_de_uso_grupo', 
    'ca_total', 'ind_outlier', 'bairro_limpo', 'distrito_definitivo'
]